# THE FOLLOWING IS GENERATED BY GEMINI FROM TEH ORIGINAL SCRIPT WHICH IS BELOW THE GENERATED CODE

# #!/usr/bin/env bash

# # ==============================================================================
# # 1. Unofficial Bash Strict Mode & Error Handling
# # ==============================================================================
# # -e: Exit immediately if a command fails
# # -u: Exit if an unset variable is used
# # -o pipefail: Catch errors in piped commands
# set -euo pipefail

# # Logging colors
# readonly RED='\033[0;31m'
# readonly GREEN='\033[0;32m'
# readonly BLUE='\033[0;34m'
# readonly YELLOW='\033[0;33m'
# readonly NC='\033[0m' # No Color

# log_info()    { echo -e "${BLUE}[INFO]${NC} $1"; }
# log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
# log_warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
# log_err()     { echo -e "${RED}[ERROR]${NC} $1" >&2; }

# # Trap unexpected errors to print the exact line it failed on
# trap 'log_err "An error occurred on line $LINENO. Exiting..."; exit 1' ERR

# # ==============================================================================
# # 2. Sudo Authentication & Keep-Alive
# # ==============================================================================
# log_info "Prompting for sudo password upfront..."
# sudo -v
# # Keep-alive: update existing sudo time stamp until script has finished
# while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# # ==============================================================================
# # 3. Package Management
# # ==============================================================================
# log_info "Updating and upgrading packages..."
# sudo apt-get update -y
# # DEBIAN_FRONTEND ensures apt doesn't throw weird interactive dialog boxes
# sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -y

# log_info "Installing core packages..."
# sudo apt-get install -y tmux gh git build-essential ripgrep unzip xclip curl fzf bat fd-find

# # ==============================================================================
# # 4. Git & GitHub Setup
# # ==============================================================================
# log_info "Setting up Git..."
# git config --global user.email "tahzib404@gmail.com"
# git config --global user.name "glutonium69"
# log_success "Git configured."

# log_info "Setting up GitHub CLI..."
# # Check if already authenticated before prompting
# if ! gh auth status &>/dev/null; then
#     gh auth login
# else
#     log_warn "GitHub CLI already authenticated. Skipping login."
# fi
# gh repo list || log_err "Failed to list repos. Make sure GH CLI is authenticated."

# # ==============================================================================
# # 5. Node, NVM, NPM
# # ==============================================================================
# log_info "Setting up NVM, Node, and NPM..."
# if [ ! -d "$HOME/.nvm" ]; then
#     curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
# else
#     log_warn "NVM already installed. Skipping download."
# fi

# # We must load NVM directly into the current script's environment to use it
# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# nvm install node
# log_success "Node & NPM installed."

# # ==============================================================================
# # 6. Cloning Repositories
# # ==============================================================================
# log_info "Cloning shell custom repo..."
# if [ ! -d "$HOME/.shell_custom_config" ]; then
#     git clone https://github.com/glutonium69/my_shell_configs "$HOME/.shell_custom_config"
# else
#     log_warn "Shell config repo already exists. Pulling latest..."
#     git -C "$HOME/.shell_custom_config" pull
# fi

# log_info "Cloning Neovim kickstart config..."
# # Safely fall back to ~/.config if XDG_CONFIG_HOME is empty
# CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
# if [ ! -d "$CONFIG_HOME/nvim" ]; then
#     git clone --branch edit-1 --single-branch https://github.com/glutonium69/kickstart.nvim "$CONFIG_HOME/nvim"
# else
#     log_warn "Neovim config already exists. Pulling latest..."
#     git -C "$CONFIG_HOME/nvim" pull
# fi

# # ==============================================================================
# # 7. Symlinks and .bashrc Injection
# # ==============================================================================
# log_info "Enabling custom shell configs..."
# # -s for symlink, -f to force overwrite if it already exists
# ln -sf "$HOME/.shell_custom_config/tmux.conf" "$HOME/.tmux.conf"

# # Only append to .bashrc if the line isn't already there (Idempotency)
# if ! grep -q 'source "$HOME/.shell_custom_config/init.sh"' "$HOME/.bashrc"; then
#     echo '' >> "$HOME/.bashrc"
#     echo 'source "$HOME/.shell_custom_config/init.sh"' >> "$HOME/.bashrc"
#     log_success "Appended custom.sh to .bashrc"
# else
#     log_warn "custom.sh is already sourced in .bashrc. Skipping."
# fi

# # ==============================================================================
# # 8. Tmux Plugin Manager
# # ==============================================================================
# log_info "Setting up Tmux Plugin Manager (TPM)..."
# if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
#     git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
# else
#     log_warn "TPM already installed. Skipping clone."
# fi

# if [ -f "$HOME/.tmux/plugins/tpm/bin/install_plugins" ]; then
#     "$HOME/.tmux/plugins/tpm/bin/install_plugins"
# fi

# # ==============================================================================
# # 9. Neovim Installation
# # ==============================================================================
# log_info "Cleaning up old Neovim installations..."
# rm -rf ~/.local/share/nvim ~/.cache/nvim ~/.local/state/nvim
# sudo apt-get remove -y neovim || true # '|| true' ignores the error if it wasn't installed

# log_info "Installing the latest stable Neovim AppImage..."
# # Best practice: Download to /tmp, then move to /usr/local/bin to avoid conflict with apt
# NVIM_TEMP="/tmp/nvim-linux-x86_64.appimage"
# wget -qO "$NVIM_TEMP" https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage
# chmod u+x "$NVIM_TEMP"
# sudo mv "$NVIM_TEMP" /usr/local/bin/nvim
# log_success "Neovim installed successfully."

# log_success "=========================================================="
# log_success "Setup complete! Please close and reopen terminal."
# log_success "=========================================================="

# ORIGINAL SCRIPT

#!/usr/bin/bash

echo "==========================="
echo "updating and upgrading pkgs"
echo "==========================="
sudo apt update
sudo apt upgrade

echo "==============="
echo "installing pkgs"
echo "==============="
sudo apt install tmux gh git build-essential ripgrep unzip xclip curl fzf bat fd-find

echo "============="
echo "setting up gh"
echo "============="
gh auth login
gh repo list

echo "=============="
echo "setting up git"
echo "=============="
git config --global user.email "tahzib404@gmail.com"
git config --global user.name "glutonium69"

echo "======================"
echo "setting nvm, node, npm"
echo "======================"
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
source .bashrc
nvm install node

echo "========================="
echo "cloning shell custom repo"
echo "========================="
git clone https://github.com/glutonium69/my_shell_configs "$HOME/.shell_custom_config"

echo "====================="
echo "cloning neovim config"
echo "====================="
git clone --branch edit-1 --single-branch https://github.com/glutonium69/kickstart.nvim "$XDG_CONFIG_HOME/nvim"

echo "===================================="
echo "enabling custom shell configs setups"
echo "===================================="
ln -s "$HOME/.shell_custom_config/tmux.conf" "$HOME/.tmux.conf"
echo '' >> "$HOME/.bashrc"
echo 'source "$HOME/.shell_custom_config/init.sh"' >> "$HOME/.bashrc"

echo "================================================"
echo "setting up tmux plugin manager and other plugins"
echo "================================================"
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
chmod +x ./.tmux/plugins/tpm/bin/install_plugins
./.tmux/plugins/tpm/bin/install_plugins

echo "==============="
echo "setting up nvim"
echo "==============="
rm -rf ~/.local/share/nvim
rm -rf ~/.cache/nvim
rm -rf ~/.local/state/nvim
sudo apt remove neovim

echo "==============="
echo "installing the latest stable version of nvim"
echo "==============="
cd ~
wget https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage
chmod u+x nvim-linux-x86_64.appimage
sudo mv nvim-linux-x86_64.appimage /usr/bin/nvim

